version: 0.5.5.{build}

init:
  - ps: if ($env:APPVEYOR_REPO_TAG_NAME) { Update-AppveyorBuild -Version $env:APPVEYOR_REPO_TAG_NAME.Substring(1) }

platform:
  - Any CPU

configuration:
  - Release

matrix:
  fast_finish: true

assembly_info:
  patch: true
  file: AssemblyInfo.cs
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

cache:
  - packages -> **\packages.config

environment:
  COVERALLS_REPO_TOKEN:
    secure: AO3IDJhJX5ipKoF6ocupCLqns27es3j/2I4Dt/AnOdbTgYKriuXSyRBAjBAKn6Wi

before_build:
  - ps: nuget restore "$env:APPVEYOR_BUILD_FOLDER\Nancy.AttributeRouting.sln"

before_test:
  - ps: dir "$env:APPVEYOR_BUILD_FOLDER\Nancy.AttributeRouting.Tests\bin\$env:CONFIGURATION\"

test_script:
  - cinst opencover coveralls.io -source https://nuget.org/api/v2/
  - OpenCover.Console.exe -register:user -filter:"+[Nancy.AttributeRouting]*" -excludebyattribute:*.ExcludeFromCodeCoverage* -target:"%XUNIT20%\xunit.console.exe" -targetargs:"""%APPVEYOR_BUILD_FOLDER%\Nancy.AttributeRouting.Tests\bin\%CONFIGURATION%\Nancy.AttributeRouting.Tests.dll"" -noshadow -appveyor" -output:coverage.xml -returntargetcode
  - coveralls.net --opencover coverage.xml

artifacts:
  - path: 'Nancy.AttributeRouting\**\*.nupkg'
  - path: coverage.xml

nuget:
  account_feed: false
  project_feed: false
  disable_publish_on_pr: true

deploy:
  - release: v$(APPVEYOR_BUILD_VERSION)
    provider: GitHub
    draft: false
    prerelease: false
    auth_token:
      secure: cApkFZuYfz7loLotMfbhb53ZIfjjfbY7dr46eu6Q9+yAV+KuSGYGcVTG8Bgx8wka
    on:
      appveyor_repo_tag: true
  - provider: NuGet
    api_key:
      secure: iBKdOaX4b1BDwWzGKoqbHoJHyOAxL6EHCRIretKb16QRLm5l1nkaF+W0SGfuEfMY
    on:
      appveyor_repo_tag: true
  - provider: NuGet
    server: https://www.myget.org/F/lijunle/api/v2/package
    symbol_server: https://nuget.symbolsource.org/MyGet/lijunle
    api_key:
      secure: 8wzaNPk1mfp5TWFmpGIAs7XRcB9LF9NJKMkdm0oUN1q6SwQ/VVd6r9WPcDm0IXlu
    on:
      branch: master
