version: 0.5.4.{build}

init:
  - ps: if ($env:APPVEYOR_REPO_TAG_NAME) { Update-AppveyorBuild -Version $env:APPVEYOR_REPO_TAG_NAME.Substring(1) }

platform:
  - Any CPU

configuration:
  - Release

matrix:
  fast_finish: true

assembly_info:
  patch: true
  file: AssemblyInfo.cs
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

cache:
  - packages -> **\packages.config

before_build:
  - ps: nuget restore "$env:APPVEYOR_BUILD_FOLDER\Nancy.AttributeRouting.sln"

before_test:
  - ps: dir "$env:APPVEYOR_BUILD_FOLDER\Nancy.AttributeRouting.Tests\bin\$env:CONFIGURATION\"

artifacts:
  - path: '**\*.nupkg'

nuget:
  account_feed: false
  project_feed: false
  disable_publish_on_pr: true
