platform:
  - Any CPU

configuration:
  - Debug
  - Release

matrix:
  fast_finish: true

cache:
  - packages -> **\packages.config

before_build:
  - ps: nuget restore "$env:APPVEYOR_BUILD_FOLDER\Nancy.AttributeRouting.sln"

before_test:
  - ps: dir "$env:APPVEYOR_BUILD_FOLDER\Nancy.AttributeRouting.Tests\bin\$env:CONFIGURATION\"
